[files]
extend-exclude = [
    ".git",
    "target",
    "testdata",
    "Cargo.toml",
    "Cargo.lock",
    "*.json",
    "*.js",
    "**/tests/**",
    "**/test/**",
    "**/*_test.*",
    "**/*_tests.*",
    "crates/wallets/src/wallet_browser/app/assets/",
    "**/CHANGELOG.md",
]

[default.extend-words]
ser = "ser"
froms = "froms"
consts = "consts"
Arguements = "Arguements"
Lod = "Lod"
